### ISSUE TITLE
forceCrashScreen = Game does not exit

### ISSUE THREAD

**Issue by TheButterbrotMan** [natanfudge/Not-Enough-Crashes#117] opened 2022-01-21 23:22 UTC
**Describe the bug**
When i use the the forceCrashScreenOption = true, Minecraft will instant of shut down running in the background, java need to be killed via taskmanager

**To Reproduce**
1. https://www.curseforge.com/minecraft/modpacks/deathdusk (Download)
2. Click on Exit
3. Does run in background
**Crash Log:**
https://bytebin.lucko.me/7H6BZCgwqc

I dont know if this is how it should be, just wanted to notify you.

**Comment by TheButterbrotMan** [comment] 2022-01-21 23:23
#115 #110 #101

**Comment by natanfudge** [comment] 2022-01-22 11:38
Thank you for reporting, this is a duplicate of #110 essentially.

**Closed as completed by natanfudge** 2022-01-22 11:38 UTC
