### ISSUE TITLE
i18n encoding error

### ISSUE THREAD

**Issue by rsp4jack** [natanfudge/Not-Enough-Crashes#105] opened 2021-12-11 08:04 UTC
This is Chinese i18n:
![image](https://user-images.githubusercontent.com/47512866/145669343-e6a67287-f7e7-4cb1-be20-2d25226bdb45.png)

**Comment by natanfudge** [comment] 2021-12-15 06:41
Hey, thanks for reporting. I'll take a look at this soon.

**Comment by natanfudge** [comment] 2021-12-17 11:15
I can't reproduce this.

**Comment by SettingDust** [comment] 2022-01-12 05:08
![图片](https://user-images.githubusercontent.com/19922286/149065782-dbe8130f-b44a-480d-8527-0504a0e3ad2e.png)
There are two issue here:
1. NEC won't load the lang file from resourcepack. I have to replace the file in jar for testing and translating. Of course, a restart is required. It's complex.
2. https://github.com/natanfudge/Not-Enough-Crashes/blob/1.16/common/src/main/java/fudge/notenoughcrashes/utils/NecLocalization.java#L80 will load lang file with different charset in different system or jvm options. It's caused this "bug". After I replace the file in jar with a GBK version, it's fine

But I don't think charset read file should be specific to UTF-8. I don't know what's the problem you face let you choose implement it yourself. Using `ResourceManager` is a better solution for load lang files.

**Comment by natanfudge** [comment] 2022-01-12 06:04
The issue was that a resource loader was not always available (e.g. in fabric with no fabric api). I'll look at other ways of doing this.

**Comment by natanfudge** [comment] 2022-01-14 11:09
Fixed in 4.1.4

**Closed as completed by natanfudge** 2022-01-14 11:09 UTC

**Comment by SettingDust** [comment] 2022-01-14 13:28
> Fixed in 4.1.4

Will it backport to 1.16?

**Comment by natanfudge** [comment] 2022-01-14 14:20
Yeah I'll backport it.
