### ISSUE TITLE
Unable to load this mod with Sodium 0.5.0 | Fabric 1.20.1 

### ISSUE THREAD

**Issue by makumaku1974** [natanfudge/Not-Enough-Crashes#176] opened 2023-08-12 11:46 UTC
**Describe the bug**

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.5.0 with version 0.5.0 that is compatible with:
		 - notenoughcrashes 4.4.6+1.20.1
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.5.0 is incompatible with any version of mod 'Not Enough Crashes' (notenoughcrashes), but a matching version is present: 4.4.6+1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**To Reproduce**

**Crash Log:**
Link to the crash log, if relevant. You can upload a crash log by using [crashy](https://crashy.net/). 

**Game Instance:**
Link to the curseforge/multimc game instance, or to a zip containing your game instance. For most issues, you must provide _something_ including the mods, saves, and configs you have used.

**Comment by natanfudge** [comment] 2023-08-12 12:57
Duplicate of #175

**Closed as completed** 2023-08-12 12:57 UTC
