### ISSUE TITLE
1.16.3 Not enough crashes mod Crash report: Desc Nopointer crash

### ISSUE THREAD

**Issue by Kylebartaous** [natanfudge/Not-Enough-Crashes#25] opened 2020-10-18 18:53 UTC
Minecraft version: 1.16.3
Fabric Loader version: fabric-loader-0.10.2+build.210-1.16.3
Fabric API version: fabric-API-0.24.0+build.411-1.16.jar

Lastest Logs: https://pastebin.com/Dj7gKZFL
Crash Log: https://pastebin.com/fvLjZpka

**Comment by Kylebartaous** [comment] 2020-10-18 23:11
Bit more testing

Test #1:

Minecraft version: 1.16.3
Fabric Loader version: fabric-loader-0.10.2+build.210-1.16.3
Fabric API version: fabric-API-0.24.1+build.412-1.16
Fabric mod menu version: mod menu-1.14.6+build.31
Not enough crashes mod version: not enough crashes-2.1.4+1.16.2

Crash report: https://pastebin.com/fvLjZpka
Lastest logs: https://pastebin.com/HQyEQZyp

Notes for test #1: Tested with a fresh profile on the twitch app, the crash report & latest logs look somewhat the same from the first post, tho putting it in any-ways since it's only loading the basic stuff, of the mod & the parts of the fabric that are needed. It crashes at startup, I am unable, at least on my screen, able to see any render of the loading screen starts, other than the background loading part.

Test #2 

Minecraft version: 1.16.3
Fabric Loader version: fabric-loader-0.10.2+build.210-1.16.3
Fabric API version: fabric-API-0.24.1+build.412-1.16
Fabric mod menu version: mod menu-1.14.6+build.31
Not enough crashes mod version: not enough crashes-2.1.4+1.16.2

Crash Report: https://pastebin.com/HtJ9jw6S
Latest Log: https://pastebin.com/h05Mv596

Notes for test #2: Running pretty much the same test as the first thread post, main modest modpack, did a check for updates & see if there are any missing bits, like lib files. turned off any other mods I know that already have a problem that leads to crashes. testing it again to see if the same type of crash happens w/ in the crash report/logs to see if it's a reproducible issue. Same happens at wrote in the notes for test #1, I do not get past the starting loading screen.

mods turned off
* - the author mod is known to cause a crash on its own, made a crash report on it also, link to it, wasn't sure if I had it on or off before then I made the first post

**Comment by Diamondman121314** [comment] 2020-10-20 00:38
Something to add to this issue. Crash is caused by something with Fabric Loader 0.10.2+build.210. Not Enough Crashes works fine with Loader 0.10.1+build.209.

**Comment by natanfudge** [comment] 2020-10-20 03:14
Hey, thanks for the bug report. 
Unfortunately I won't be able to make any code changes for a while. I wouldn't hold it against anyone if they made a fork, even if it would take me only a few weeks until I could update the code again.

**Comment by i509VCB** [comment] 2020-10-20 04:16
Seems to have been an issue with Fabric Loader's json migration, a fix is open: https://github.com/FabricMC/fabric-loader/pull/324. When modmuss or player has time, one of them will merge the fix and release a new build.

**Comment by natanfudge** [comment] 2020-10-20 16:15
This should be fixed in the latest fabric build

**Closed by natanfudge** 2020-10-20 16:15 UTC
